language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mariusstoica/docker-react -f Dockerfile .

script:
  - docker run -e CI=true mariusstoica/docker-react npm run test 

deploy: 
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-346704589042"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
